var searchData=
[
  ['backgroundtimerservice_2edroid_2ecs',['BackgroundTimerService.Droid.cs',['../_background_timer_service_8_droid_8cs.html',1,'']]],
  ['backgroundtimerservice_2eios_2ecs',['BackgroundTimerService.IOS.cs',['../_background_timer_service_8_i_o_s_8cs.html',1,'']]],
  ['basepagerenderer_2edroid_2ecs',['BasePageRenderer.Droid.cs',['../_base_page_renderer_8_droid_8cs.html',1,'']]],
  ['basepagerenderer_2eios_2ecs',['BasePageRenderer.IOS.cs',['../_base_page_renderer_8_i_o_s_8cs.html',1,'']]],
  ['basepages_2ecs',['BasePages.cs',['../_base_pages_8cs.html',1,'']]],
  ['basetabbedpage_2ecs',['BaseTabbedPage.cs',['../_base_tabbed_page_8cs.html',1,'']]],
  ['basetabbedpagerenderer_2edroid_2ecs',['BaseTabbedPageRenderer.Droid.cs',['../_base_tabbed_page_renderer_8_droid_8cs.html',1,'']]],
  ['basetabbedpagerenderer_2eios_2ecs',['BaseTabbedPageRenderer.IOS.cs',['../_base_tabbed_page_renderer_8_i_o_s_8cs.html',1,'']]],
  ['beginanimationbehavior_2ecs',['BeginAnimationBehavior.cs',['../_begin_animation_behavior_8cs.html',1,'']]],
  ['bindingcontextbehavior_2ecs',['BindingContextBehavior.cs',['../_binding_context_behavior_8cs.html',1,'']]],
  ['blah_2ecs',['blah.cs',['../blah_8cs.html',1,'']]],
  ['bluroverlay_2edroid_2ecs',['BlurOverlay.Droid.cs',['../_blur_overlay_8_droid_8cs.html',1,'']]],
  ['bluroverlay_2eios_2ecs',['BlurOverlay.IOS.cs',['../_blur_overlay_8_i_o_s_8cs.html',1,'']]],
  ['booleantoobjectconverter_2ecs',['BooleanToObjectConverter.cs',['../_boolean_to_object_converter_8cs.html',1,'']]],
  ['boundcontenview_2ecs',['BoundContenView.cs',['../_bound_conten_view_8cs.html',1,'']]],
  ['boundmasterdetailpage_2ecs',['BoundMasterDetailPage.cs',['../_bound_master_detail_page_8cs.html',1,'']]],
  ['boundpage_2ecs',['BoundPage.cs',['../_bound_page_8cs.html',1,'']]],
  ['businessbase_2ecs',['BusinessBase.cs',['../_business_base_8cs.html',1,'']]]
];
