var searchData=
[
  ['calendarevent_2edroid_2ecs',['CalendarEvent.Droid.cs',['../_calendar_event_8_droid_8cs.html',1,'']]],
  ['calendarevent_2eios_2ecs',['CalendarEvent.IOS.cs',['../_calendar_event_8_i_o_s_8cs.html',1,'']]],
  ['commoneffects_2ecs',['CommonEffects.cs',['../_common_effects_8cs.html',1,'']]],
  ['commoneffects_2edroid_2ecs',['CommonEffects.Droid.cs',['../_common_effects_8_droid_8cs.html',1,'']]],
  ['commoneffects_2eios_2ecs',['CommonEffects.IOS.cs',['../_common_effects_8_i_o_s_8cs.html',1,'']]],
  ['communication_2edroid_2ecs',['Communication.Droid.cs',['../_communication_8_droid_8cs.html',1,'']]],
  ['communication_2eios_2ecs',['Communication.IOS.cs',['../_communication_8_i_o_s_8cs.html',1,'']]],
  ['configurationmodel_2ecs',['ConfigurationModel.cs',['../_configuration_model_8cs.html',1,'']]],
  ['contentviewrounded_2ecs',['ContentViewRounded.cs',['../_content_view_rounded_8cs.html',1,'']]],
  ['contentviewroundedrenderer_2edroid_2ecs',['ContentViewRoundedRenderer.Droid.cs',['../_content_view_rounded_renderer_8_droid_8cs.html',1,'']]],
  ['contentviewroundedrenderer_2eios_2ecs',['ContentViewRoundedRenderer.IOS.cs',['../_content_view_rounded_renderer_8_i_o_s_8cs.html',1,'']]],
  ['contextmenuservice_2edroid_2ecs',['ContextMenuService.Droid.cs',['../_context_menu_service_8_droid_8cs.html',1,'']]],
  ['coreextensions_2ecs',['CoreExtensions.cs',['../_core_extensions_8cs.html',1,'']]],
  ['corenavigationpagerenderer_2edroid_2ecs',['CoreNavigationPageRenderer.Droid.cs',['../_core_navigation_page_renderer_8_droid_8cs.html',1,'']]],
  ['coresettings_2ecs',['CoreSettings.cs',['../_core_settings_8cs.html',1,'']]],
  ['corestyles_2ecs',['CoreStyles.cs',['../_core_styles_8cs.html',1,'']]],
  ['crosspushnotification_2ecs',['CrossPushNotification.cs',['../_cross_push_notification_8cs.html',1,'']]]
];
